In [16]:
import polars as pl

from ogden_ice_analysis import load_dataset

detentions = load_dataset("detention-stays-latest", lazy=False)
detentions.head()

shape: (5, 64)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ stay_ID   ┆ n_stints ┆ detention ┆ unique_id ┆ … ┆ detention ┆ detention ┆ book_in_d ┆ book_out_ │
│ ---       ┆ ---      ┆ _facility ┆ entifier  ┆   ┆ _facility ┆ _facility ┆ ate_time_ ┆ date_time │
│ str       ┆ i32      ┆ _codes_al ┆ ---       ┆   ┆ _last     ┆ _code_las ┆ last      ┆ _last     │
│           ┆          ┆ l         ┆ str       ┆   ┆ ---       ┆ t         ┆ ---       ┆ ---       │
│           ┆          ┆ ---       ┆           ┆   ┆ str       ┆ ---       ┆ datetime[ ┆ datetime[ │
│           ┆          ┆ str       ┆           ┆   ┆           ┆ str       ┆ μs, UTC]  ┆ μs, UTC]  │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0000004d7 ┆ 3        ┆ AUSHOLD;  ┆ 0000004d7 ┆ … ┆ AZ REM OP ┆ IWAHOLD   ┆ 2025-11-2 ┆ 2025-11-2 │
│ b875782a3 ┆          ┆ CCAHUTX;  ┆ b875782a3 ┆   ┆ COORD     ┆           ┆ 6         ┆ 8         │
│ b6f2b460f ┆          ┆ IWAHOLD   ┆ b6f2b460f ┆   ┆ CENTER    ┆           ┆ 22:15:00  ┆ 00:50:00  │
│ 98c…      ┆          ┆           ┆ 98c…      ┆   ┆ (AROCC)   ┆           ┆ UTC       ┆ UTC       │
│ 0000162b3 ┆ 2        ┆ BLBNATX;  ┆ 0000162b3 ┆ … ┆ PRAIRIELA ┆ PRLDCTX   ┆ 2023-02-2 ┆ 2023-02-2 │
│ 3f636fce8 ┆          ┆ PRLDCTX   ┆ 3f636fce8 ┆   ┆ ND        ┆           ┆ 6         ┆ 7         │
│ b114d00fa ┆          ┆           ┆ b114d00fa ┆   ┆ DETENTION ┆           ┆ 20:44:00  ┆ 01:31:00  │
│ 8d8…      ┆          ┆           ┆ 8d8…      ┆   ┆ CENTER    ┆           ┆ UTC       ┆ UTC       │
│ 0000162b3 ┆ 1        ┆ STFRCTX   ┆ 0000162b3 ┆ … ┆ SOUTH     ┆ STFRCTX   ┆ 2023-05-1 ┆ 2023-10-2 │
│ 3f636fce8 ┆          ┆           ┆ 3f636fce8 ┆   ┆ TEXAS FAM ┆           ┆ 7         ┆ 4         │
│ b114d00fa ┆          ┆           ┆ b114d00fa ┆   ┆ RESIDENTI ┆           ┆ 07:07:00  ┆ 12:45:00  │
│ 8d8…      ┆          ┆           ┆ 8d8…      ┆   ┆ AL CE…    ┆           ┆ UTC       ┆ UTC       │
│ 00001bc12 ┆ 1        ┆ FSF       ┆ 00001bc12 ┆ … ┆ FLORENCE  ┆ FSF       ┆ 2024-12-2 ┆ 2024-12-2 │
│ 8707c1bc0 ┆          ┆           ┆ 8707c1bc0 ┆   ┆ STAGING   ┆           ┆ 7         ┆ 7         │
│ f44bfd6fc ┆          ┆           ┆ f44bfd6fc ┆   ┆ FACILITY  ┆           ┆ 01:16:00  ┆ 08:48:00  │
│ c3f…      ┆          ┆           ┆ c3f…      ┆   ┆           ┆           ┆ UTC       ┆ UTC       │
│ 000021518 ┆ 6        ┆ DALHOLD;  ┆ 000021518 ┆ … ┆ River Cor ┆ RVRCCLA   ┆ 2025-10-0 ┆ 2025-11-1 │
│ 6a4071ae5 ┆          ┆ BLBNATX;  ┆ 6a4071ae5 ┆   ┆ rectional ┆           ┆ 5         ┆ 3         │
│ bc250f63e ┆          ┆ PRLDCTX;  ┆ bc250f63e ┆   ┆ Center    ┆           ┆ 11:36:00  ┆ 17:04:00  │
│ 6ba…      ┆          ┆ PIN…      ┆ 6ba…      ┆   ┆           ┆           ┆ UTC       ┆ UTC       │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [17]:
facilities = load_dataset("facilities-latest", lazy=False)
facilities.head()

shape: (5, 24)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ detention ┆ name      ┆ address   ┆ city      ┆ … ┆ average_d ┆ average_m ┆ max_daily ┆ max_midn │
│ _facility ┆ ---       ┆ ---       ┆ ---       ┆   ┆ aily_popu ┆ idnight_p ┆ _populati ┆ ight_pop │
│ _code     ┆ str       ┆ str       ┆ str       ┆   ┆ lation_la ┆ opulation ┆ on_last_y ┆ ulation_ │
│ ---       ┆           ┆           ┆           ┆   ┆ st_…      ┆ _la…      ┆ ear       ┆ last_y…  │
│ str       ┆           ┆           ┆           ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ i32       ┆ i32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ IWAHOLD   ┆ AZ        ┆ 6335      ┆ Mesa      ┆ … ┆ 101.66575 ┆ 60.063014 ┆ 777       ┆ 499      │
│           ┆ Removal   ┆ South     ┆           ┆   ┆ 3         ┆           ┆           ┆          │
│           ┆ Operation ┆ Downwind, ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Coord     ┆ Suite 104 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Cen…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ABRXSPA   ┆ Abraxas   ┆ 1000      ┆ Morgantow ┆ … ┆ 0.567123  ┆ 0.561644  ┆ 5         ┆ 5        │
│           ┆ Academy   ┆ Academy   ┆ n         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Drive     ┆           ┆   ┆           ┆           ┆           ┆          │
│ ADAMSMS   ┆ Adams     ┆ 20 Hobo   ┆ Natchez   ┆ … ┆ 2197.3205 ┆ 2158.8356 ┆ 2632      ┆ 2563     │
│           ┆ County    ┆ Forks     ┆           ┆   ┆ 48        ┆ 16        ┆           ┆          │
│           ┆ Correctio ┆ Road      ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ nal Cent… ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ADDCOVT   ┆ Addison   ┆ 35 Court  ┆ Middlebur ┆ … ┆ 0.005479  ┆ 0.0       ┆ 1         ┆ 0        │
│           ┆ County    ┆ Street    ┆ y         ┆   ┆           ┆           ┆           ┆          │
│           ┆ Jail      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ADLNTCA   ┆ Adelanto  ┆ 10400     ┆ Adelanto  ┆ … ┆ 1358.5534 ┆ 1337.9068 ┆ 1981      ┆ 1932     │
│           ┆ ICE Proce ┆ Rancho    ┆           ┆   ┆ 25        ┆ 49        ┆           ┆          │
│           ┆ ssing     ┆ Road      ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Center    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [26]:
ogden_facility = facilities.filter(pl.col("zip").str.contains("84401"))
display(ogden_facility)
ogden_facility_code = ogden_facility["detention_facility_code"]

shape: (1, 24)
┌────────────┬────────────┬────────────┬───────┬───┬───────────┬───────────┬───────────┬───────────┐
│ detention_ ┆ name       ┆ address    ┆ city  ┆ … ┆ average_d ┆ average_m ┆ max_daily ┆ max_midni │
│ facility_c ┆ ---        ┆ ---        ┆ ---   ┆   ┆ aily_popu ┆ idnight_p ┆ _populati ┆ ght_popul │
│ ode        ┆ str        ┆ str        ┆ str   ┆   ┆ lation_la ┆ opulation ┆ on_last_y ┆ ation_las │
│ ---        ┆            ┆            ┆       ┆   ┆ st_…      ┆ _la…      ┆ ear       ┆ t_y…      │
│ str        ┆            ┆            ┆       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆            ┆            ┆       ┆   ┆ f64       ┆ f64       ┆ i32       ┆ i32       │
╞════════════╪════════════╪════════════╪═══════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ OGUHOLD    ┆ Ogden Hold ┆ 2487 S.    ┆ Ogden ┆ … ┆ 1.506849  ┆ 0.043836  ┆ 13        ┆ 5         │
│            ┆ Room       ┆ 1620 W     ┆       ┆   ┆           ┆           ┆           ┆           │
│            ┆            ┆ Unit E     ┆       ┆   ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴───────┴───┴───────────┴───────────┴───────────┴───────────┘

In [28]:
ogden_detentions = detentions.filter(
    pl.col("detention_facility_codes_all").str.contains(ogden_facility_code)
)
display(ogden_detentions)

shape: (947, 64)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ stay_ID   ┆ n_stints ┆ detention ┆ unique_id ┆ … ┆ detention ┆ detention ┆ book_in_d ┆ book_out_ │
│ ---       ┆ ---      ┆ _facility ┆ entifier  ┆   ┆ _facility ┆ _facility ┆ ate_time_ ┆ date_time │
│ str       ┆ i32      ┆ _codes_al ┆ ---       ┆   ┆ _last     ┆ _code_las ┆ last      ┆ _last     │
│           ┆          ┆ l         ┆ str       ┆   ┆ ---       ┆ t         ┆ ---       ┆ ---       │
│           ┆          ┆ ---       ┆           ┆   ┆ str       ┆ ---       ┆ datetime[ ┆ datetime[ │
│           ┆          ┆ str       ┆           ┆   ┆           ┆ str       ┆ μs, UTC]  ┆ μs, UTC]  │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 002e3859d ┆ 4        ┆ OGUHOLD;  ┆ 002e3859d ┆ … ┆ NEVADA    ┆ NVSDCNV   ┆ 2023-06-0 ┆ 2023-06-1 │
│ 691e936dc ┆          ┆ SLSLCUT;  ┆ 691e936dc ┆   ┆ SOUTHERN  ┆           ┆ 2         ┆ 3         │
│ ac602d12f ┆          ┆ SLCHOLD;  ┆ ac602d12f ┆   ┆ DETENTION ┆           ┆ 12:22:00  ┆ 16:46:00  │
│ 344…      ┆          ┆ NVS…      ┆ 344…      ┆   ┆ CENT…     ┆           ┆ UTC       ┆ UTC       │
│ 002e3859d ┆ 2        ┆ OGUHOLD;  ┆ 002e3859d ┆ … ┆ SALT LAKE ┆ SLSLCUT   ┆ 2024-11-1 ┆ 2024-11-1 │
│ 691e936dc ┆          ┆ SLSLCUT   ┆ 691e936dc ┆   ┆ COUNTY    ┆           ┆ 8         ┆ 9         │
│ ac602d12f ┆          ┆           ┆ ac602d12f ┆   ┆ JAIL      ┆           ┆ 08:44:00  ┆ 13:20:00  │
│ 344…      ┆          ┆           ┆ 344…      ┆   ┆           ┆           ┆ UTC       ┆ UTC       │
│ 00cef3613 ┆ 6        ┆ OGUHOLD;  ┆ 00cef3613 ┆ … ┆ PORT      ┆ PIC       ┆ 2025-11-1 ┆ 2025-11-2 │
│ bd6de76f4 ┆          ┆ WEBERUT;  ┆ bd6de76f4 ┆   ┆ ISABEL    ┆           ┆ 8         ┆ 0         │
│ 6abba5cb5 ┆          ┆ SLCHOLD;  ┆ 6abba5cb5 ┆   ┆ SPC       ┆           ┆ 21:23:00  ┆ 04:12:00  │
│ 1a0…      ┆          ┆ FSF…      ┆ 1a0…      ┆   ┆           ┆           ┆ UTC       ┆ UTC       │
│ 0120e25b0 ┆ 1        ┆ OGUHOLD   ┆ 0120e25b0 ┆ … ┆ OGDEN     ┆ OGUHOLD   ┆ 2023-01-3 ┆ 2023-01-3 │
│ eef04f113 ┆          ┆           ┆ eef04f113 ┆   ┆ HOLD ROOM ┆           ┆ 0         ┆ 0         │
│ c41a35c92 ┆          ┆           ┆ c41a35c92 ┆   ┆           ┆           ┆ 09:58:00  ┆ 13:00:00  │
│ 874…      ┆          ┆           ┆ 874…      ┆   ┆           ┆           ┆ UTC       ┆ UTC       │
│ 015b7711f ┆ 4        ┆ OGUHOLD;  ┆ 015b7711f ┆ … ┆ FLORENCE  ┆ FSF       ┆ 2025-11-2 ┆ 2025-11-3 │
│ 75e76347a ┆          ┆ DAVISUT;  ┆ 75e76347a ┆   ┆ STAGING   ┆           ┆ 8         ┆ 0         │
│ 9239c3d26 ┆          ┆ SLCHOLD;  ┆ 9239c3d26 ┆   ┆ FACILITY  ┆           ┆ 19:02:00  ┆ 08:30:00  │
│ 21d…      ┆          ┆ FSF       ┆ 21d…      ┆   ┆           ┆           ┆ UTC       ┆ UTC       │
│ …         ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ fe795f699 ┆ 3        ┆ OGUHOLD;  ┆ fe795f699 ┆ … ┆ NEVADA    ┆ NVSDCNV   ┆ 2025-05-0 ┆ 2025-07-0 │
│ b660e6abb ┆          ┆ SLCHOLD;  ┆ b660e6abb ┆   ┆ SOUTHERN  ┆           ┆ 9         ┆ 3         │
│ 583b0f39d ┆          ┆ NVSDCNV   ┆ 583b0f39d ┆   ┆ DETENTION ┆           ┆ 17:45:00  ┆ 10:57:00  │
│ a7a…      ┆          ┆           ┆ a7a…      ┆   ┆ CENT…     ┆           ┆ UTC       ┆ UTC       │
│ fea0dc29f ┆ 6        ┆ OGUHOLD;  ┆ fea0dc29f ┆ … ┆ ADELANTO  ┆ ADLNTCA   ┆ 2025-06-0 ┆ 2025-06-2 │
│ 19d23f923 ┆          ┆ SLCHOLD;  ┆ 19d23f923 ┆   ┆ ICE PROCE ┆           ┆ 8         ┆ 8         │
│ b32ccd56a ┆          ┆ UINTAWY;  ┆ b32ccd56a ┆   ┆ SSING     ┆           ┆ 11:40:00  ┆ 16:50:00  │
│ de0…      ┆          ┆ SLC…      ┆ de0…      ┆   ┆ CENTER    ┆           ┆ UTC       ┆ UTC       │
│ ff52ae401 ┆ 5        ┆ OGUHOLD;  ┆ ff52ae401 ┆ … ┆ NEVADA    ┆ NVSDCNV   ┆ 2023-05-1 ┆ 2023-06-1 │
│ 2e51e06a8 ┆          ┆ SLSLCUT;  ┆ 2e51e06a8 ┆   ┆ SOUTHERN  ┆           ┆ 9         ┆ 3         │
│ 6741bf05a ┆          ┆ SLCHOLD;  ┆ 6741bf05a ┆   ┆ DETENTION ┆           ┆ 17:10:00  ┆ 16:46:00  │
│ 229…      ┆          ┆ NYE…      ┆ 229…      ┆   ┆ CENT…     ┆           ┆ UTC       ┆ UTC       │
│ ff58b6f47 ┆ 2        ┆ OGUHOLD;  ┆ ff58b6f47 ┆ … ┆ DAVIS CO. ┆ DAVISUT   ┆ 2025-11-1 ┆ 2025-11-1 │
│ 3fa858487 ┆          ┆ DAVISUT   ┆ 3fa858487 ┆   ┆ JAIL      ┆           ┆ 3         ┆ 4         │
│ 07c317ccd ┆          ┆           ┆ 07c317ccd ┆   ┆           ┆           ┆ 12:45:00  ┆ 13:45:00  │
│ 6a1…      ┆          ┆           ┆ 6a1…      ┆   ┆           ┆           ┆ UTC       ┆ UTC       │
│ ff6200ded ┆ 1        ┆ OGUHOLD   ┆ ff6200ded ┆ … ┆ OGDEN     ┆ OGUHOLD   ┆ 2023-03-1 ┆ 2023-03-1 │
│ f8f1c29ff ┆          ┆           ┆ f8f1c29ff ┆   ┆ HOLD ROOM ┆           ┆ 6         ┆ 6         │
│ d18fe475c ┆          ┆           ┆ d18fe475c ┆   ┆           ┆           ┆ 07:00:00  ┆ 10:18:00  │
│ 955…      ┆          ┆           ┆ 955…      ┆   ┆           ┆           ┆ UTC       ┆ UTC       │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘